version: '3'

services:

  autos:
    build: ./microservices/auto-service
    depends_on:
            - mongoaut
    environment:
            - MONGODB_URI=mongodb://mongoaut:27017/autos
  mongoaut: 
    container_name: mimongoautos
    image: mongo
    ports: 
        - "27017:27017"


  conceptos:
    build: ./microservices/concepto-service
    depends_on:
          - mongocon
    environment:
          - MONGODB_CNN=mongodb://mongocon:27017/conceptos
  mongocon: 
      container_name: mimongoconceptos
      image: mongo
      ports: 
        - "27018:27017"

  nginx:
      image: nginx:latest
      ports:
        - "8081:8081"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - autos
        - conceptos


    